##@ Build

.PHONY: build
build-server:
	g++ -o hello_world_server server.cpp

.PHONY: clean
clean: ## Delete the binaries generated by the build-server target and/or from the test execution
	rm -f hello_world_server hello_world_server_test
	rm -Rf gtest_install_workspace

.PHONY: test
test: ## Unit testing using gtest
	g++ -std=c++11 -o hello_world_server_test server_unittest.cpp -lgtest -lgtest_main -lpthread -DSERVER_TEST
	./hello_world_server_test

.PHONY: run
run: ## Compile the server and run it
	g++ -o hello_world_server server.cpp
	@echo "Starting server, you can browse using http://localhost:8080"
	./hello_world_server

.PHONY: install-gtest
install-gtest: ## Install gtest. Source - https://github.com/google/googletest/blob/main/googletest/README.md
	git clone https://github.com/google/googletest.git -b v1.12.x && \
	cd googletest && \
	mkdir build && \
	cd build && \
	cmake .. && \
	make && \
	make install
