##@ Build

CXX      := g++
CXXFLAGS := -std=c++11 -Wall -Wextra -O0 -g

.PHONY: build
# build everything (server + test binaries + vuln example)
build: build-server build-getsvuln

.PHONY: build-server
build-server:
	$(CXX) $(CXXFLAGS) -o hello_world_server server.cpp

.PHONY: build-getsvuln
# compile the gets_vuln.cpp example into a test binary named gets_vuln
build-getsvuln:
	$(CXX) $(CXXFLAGS) -o gets_vuln gets_vuln.cpp

.PHONY: clean
clean: ## Delete the binaries generated by the build-server target and/or from the test execution
	rm -f hello_world_server hello_world_server_test gets_vuln
	rm -Rf gtest_install_workspace

.PHONY: test
test: ## Unit testing using gtest
	$(CXX) $(CXXFLAGS) -o hello_world_server_test server_unittest.cpp -lgtest -lgtest_main -lpthread -DSERVER_TEST
	./hello_world_server_test

.PHONY: run
run: ## Compile the server and run it
	$(CXX) $(CXXFLAGS) -o hello_world_server server.cpp
	@echo "Starting server, you can browse using http://localhost:8080"
	./hello_world_server

.PHONY: run-getsvuln
# run the gets example (interactive)
run-getsvuln: build-getsvuln
	@echo "Running gets_vuln (it will prompt for input)."
	./gets_vuln

.PHONY: install-gtest
install-gtest: ## Install gtest. Source - https://github.com/google/googletest/blob/main/googletest/README.md
	git clone https://github.com/google/googletest.git -b v1.12.x && \
	cd googletest && \
	mkdir build && \
	cd build && \
	cmake .. && \
	make && \
	make install
